blueprint:
  name: Philips Tap Dial Switch for Scene control
  description: 'Use the four buttons to assign your own actions. The dial is ignored'
  source_url: https://github.com/kulve/ha-blueprints-nnmalex/blob/main/philips_tap_dial_switch.yaml
  domain: automation
  input:
    remote:
      name: Philips Hue Tap Switch
      selector:
        device:
          integration: zha
          manufacturer: Signify Netherlands B.V.
          model: RDM002
          multiple: false
    button_1_press:
      name: Button 1 Press
      description: Action to run in a single press of button 1
      default: []
      selector:
        action: {}
    button_2_press:
      name: Button 2 Press
      description: Action to run in a single press of button 2
      default: []
      selector:
        action: {}
    button_3_press:
      name: Button 3 Press
      description: Action to run in a single press of button 3
      default: []
      selector:
        action: {}
    button_4_press:
      name: Button 4 Press
      description: Action to run in a single press of button 4
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

variables:
  event: '{{ trigger.event.data.command }}'
  scene: "{{ trigger.event.data.args[1] }}"

trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input remote
action:
  - choose:
    # Buttons
    - conditions:
      - '{{ event == "recall" }}'
      - '{{ scene == 1 }}'
      sequence: !input button_1_press
    - conditions:
      - '{{ event == "recall" }}'
      - '{{ scene == 0 }}'
      sequence: !input button_2_press
    - conditions:
      - '{{ event == "recall" }}'
      - '{{ scene == 5 }}'
      sequence: !input button_3_press
    - conditions:
      - '{{ event == "recall" }}'
      - '{{ scene == 4 }}'
      sequence: !input button_4_press
